### ISSUE TITLE
Collect # of assets that load before document complete vs fully loaded

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/pagexray#17]
We currently capture asset # of fully loaded, but with a lot of sites pushing resource loading until after the onload event it may be an interesting stat to capture how much is loaded before vs after the onload event. This could also be interesting to see for things like the 1st party vs 3rd party asset comparison. It could also be used to flag where a development group should focus their efforts on improving overall front-end site performance. We could also leverage this in coach to give the user suggestions on moving assets to after the onload event improve percieved page load time.

**Comment by soulgalore** [comment]
@beenanner yes that would be cool. I wonder: today our default time is to wait seconds after the onload event (in bt/sitespeed.io) maybe we should make that higher. 

but lets start to add it here.

**Comment by beenanner** [comment]
Hmm do we surface onLoadEnd events from the navigation timing API in browsertime? Might need to add that by default first.

**Comment by soulgalore** [comment]
Yes we have that in the HAR, but I think for it to work good, we probably should wait until we fixed fullyLoaded and maybe  https://github.com/sitespeedio/browsertime/issues/186

**Comment by soulgalore** [comment]
@beenanner I've added so we collect the number of requests that happens after DOMContentLoaded and request after onLoad (and the transfer size). Is that what you are looking for?

**Comment by beenanner** [comment]
Yep that sound perfect. Let's close this one with those additions!
