### ISSUE TITLE
Number of requests and sum of number of request per content type don't match

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/pagexray#19]
Got a bug report where it don't match, aftonbladet should be one site where we have problem, lets add a test case.

**Comment by soulgalore** [comment]
ping @tobli thinking we should fix it in your new branch. We got the problem in <code>test/files/contentTypes/aftonbladet.se.har</code>

**Comment by soulgalore** [comment]
Ah I see: we only count 200 for content types (reasonable). Lets discuss how we should handle that.

**Comment by beenanner** [comment]
Not the most elegant solution, but pushes any non200s to an "other" group. We could expand requests in each type to be an object of response code counts instead? I think we would still need a other for potential unknown types though.

**Comment by soulgalore** [comment]
Since we haven't done anything with this for 5 years lets close it!
