### ISSUE TITLE
Streamed media content type is not appearing in the stats

### ISSUE THREAD

**Issue by vio** [sitespeedio/pagexray#27]
Streamed `mp4` / `mp3` are served with a `206` status code and they are skipped by pagexray collect process.

---

Testing https://codepen.io/vio/pen/KqWLEB, the `mp4` request:
- 🆗  is present in `assets`:  https://gist.github.com/vio/0825b952379b63ad8c73564c76f8d961#file-pagexray-run-0-json-L169
- 🚫  is not included into the `contentTypes` statistics: https://gist.github.com/vio/0825b952379b63ad8c73564c76f8d961#file-pagexray-run-0-json-L252

**Comment by soulgalore** [comment]
Hey @vio great find! I'll make sure to fix it before the next release this weekend or if you have time to send a PR that would be great!

Best
Peter

**Comment by soulgalore** [comment]
Merged, releasing later today.
