### ISSUE TITLE
Pagexray.summary and Pagexray.pagesummary values differ

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/pagexray#30]
Testings out the elasticsearch support I noticed these are storing their values differently one being a string and the other being a number. We should standardize on a number so pagexray.summary should be modified to cast it's values to numbers.

**Comment by beenanner** [comment]
See https://github.com/sitespeedio/sitespeed.io/pull/1644

**Comment by soulgalore** [comment]
@beenanner I think the .summary is calculated in sitespeed?
