### ISSUE TITLE
Dealing with assets folder size

### ISSUE THREAD

**Issue by mscrivo** [sitespeedio/pagexray#61]
Is there a best practice for dealing with the growth of the assets folder?  I was not able to find one and this folder grows to eventually fill up our 1 TB drive every couple of months.

**Comment by soulgalore** [comment]
Hi @mscrivo just so I understand: it's the assets like the result with HTML/images and videos you mean right? There's some documentation on how you can disable parts: https://www.sitespeed.io/documentation/sitespeed.io/best-practice/#handling-big-amount-of-data

In practice I never store the data for so long. For example if the data land on S3, I set my bucket to remove everything older than 2 weeks, just so I have enough data to find a problem and compare with what it looked like before. 

Or what's your use case?
Best
Peter

**Comment by mscrivo** [comment]
yeah, talking specifically about the files in graphite/whisper/sitespeed_io/default/pageSummary/<site name>/.../pagexray/assets

We also have it trying to delete files older than 30 days out of that folder, but for some reason, (I think path names are too long), it's not working and I end up having to delete the whole folder manually

**Comment by soulgalore** [comment]
Aha ok. For Graphite you need to configure how long you wanna keep metrics, checkout https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#configure-graphite and Etsys documentation: https://github.com/etsy/statsd/blob/master/docs/graphite.md

Hope that helps!
Best
Peter

**Comment by mscrivo** [comment]
Thank you, that's what i was looking for.

**Comment by soulgalore** [comment]
Great, closing this then.
