### ISSUE TITLE
Denied access while trying to setup a PR

### ISSUE THREAD

**Issue by rohit-nair** [sitespeedio/pagexray#70]
While uploading HAR files on https://compare.sitespeed.io to compare, it failed with following error:

![image](https://user-images.githubusercontent.com/6608672/51416656-afe9d800-1b37-11e9-9ddc-69f139a40dd8.png)

Essentially, a null check is required at lines 194 and 199 on index.js.

While trying to create a branch to setup a PR, I got access denied.

If you see this, could you put in the fix or give me access so that I could setup a PR.

Cheers.

**Comment by soulgalore** [comment]
Hi @rohit-nair could you show me what kind of error you get for the PR, you should be able to do it?

For the bug, can you attach a HAR in a gist, then I can use it when I test it out?

Best
Peter

**Comment by rohit-nair** [comment]
Thanks @soulgalore for taking the time to respond.

It looks like an issue with how the HAR file is read coz I see the entry having `pageref` in original HAR but not in the response from `readHar`. So perhaps the fix should also be in where the HAR is being read.

From File (https://gist.github.com/rohit-nair/1100a84362041de904d844c0c9cc71d0):
![image](https://user-images.githubusercontent.com/6608672/51430096-2ab40100-1bd3-11e9-92b8-36955991d645.png)

From config:
![image](https://user-images.githubusercontent.com/6608672/51430085-f8a29f00-1bd2-11e9-897b-4ea31764e212.png)

Cheers.

**Comment by rohit-nair** [comment]
Interesting. I saved from Chrome's network tab.
Will do.

**Comment by rohit-nair** [comment]
> It looks like the HAR has a couple of requests that doesn't belong to that page
I suspect tracking pixels shenanigans. They may be doing something to circumvent detection.
https://usa.kaspersky.com/blog/internet-ads-103/10546/

**Comment by rohit-nair** [comment]
Thanks @soulgalore for the help.
