### ISSUE TITLE
how to use --includeAssets in this method : pagexray.convert(har);

### ISSUE THREAD

**Issue by IMT-happy** [sitespeedio/pagexray#86]
i wanna know how to use the --includeAssets in method pagexray.convert(); and hope someone can help me. thanks

**Comment by soulgalore** [comment]
Hi @chenghuangu let me add an example in the docs, but until then, the signature is `convert: (har, config)` so you can run it like this:

`pagexray.convert(har, {includeAssets: true});`
Best
Peter

**Comment by chenghuangu** [comment]
@soulgalore i'm so lucky that you help me resolve the problem. thank you very much. 😄
